--- # Provision AWS EC2
- hosts: webservers
  become: yes
  tasks:
  - name: install nginx
    yum:
      name: nginx 
      state: latest
  - name: install php-fpm
    yum:
      name: php-fpm
      state: latest
  - name: add a php file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add some html to file
    lineinfile:
      line: "hello brave new world"
      owner: "www-data"
      path: "/var/www/html/index.html"

  

