#AWS Playbook for EC2

---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: bpmgtaws
    region: eu-west-2
    image: ami-0d18882e2647f50e7
    id: "bpmgt"
    sec_group: "{{ id }}-sec"

  tasks:
    - name: Facts
    block:

    - name: Get EC2 instance info.
      ec2_instance_info:
       aws_access_key: "{{ ec2_access_key }}"
       aws_secret_key: "{{ ec2_secret_access_key }}"
       region: "{{ region }}"
      register: result

    - name: Instance ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"

    tags: always
